apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

metadata:
  name: gohome-monitoring
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - servicemonitor.yaml
  - grafana-dashboard.yaml
