default_provider = "1password-homelab"

[providers.1password-homelab]
type = "1password"
vault = "Homelab"

[providers.1password-private]
type = "1password"
vault = "Private"

[secrets]
GITHUB_TOKEN = { provider = "1password-private", value = "Github/personal_token" }
TS_AUTHKEY = { provider = "1password-homelab", value = "gohome-secret" }
