name: Bump Version

on:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Bump version
        uses: joeds13/annover@10253f692c4c02f555e91b95f63613aa070459da # 2026.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
