name: Bump Version

on:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Bump version
        uses: joeds13/annover@71f279ea4c9fd9793bb5462c6fd9e2229bc1a62a # 2026.13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
