name: Bump Version

on:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Bump version
        uses: joeds13/annover@7e1c180c2fa23c1cd5fe608ffd92ee3f2172ac41 # 2026.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
